[project]
name = "slidgram"
description = "A Telegram/XMPP gateway"
requires-python = ">= 3.11"
dependencies = [
    "pyrofork>=2.3.55",
    "slidge>=0.2.2",
    "slidge-style-parser>=0.1.8",
    "tgcrypto>=1.2.5",
]
authors = [
    {name = "Nicolas Cedilnik", email = "nicoco@nicoco.fr"},
]
license = {file = "LICENSE"}
classifiers = [
    "Topic :: Internet :: XMPP",
]
keywords = ["xmpp", "gateway", "bridge", "instant messaging", "telegram"]
version = "0.0.0-dev0"
readme = "README.md"

[project.urls]
Homepage = "https://codeberg.org/slidge/slidgram"
Issues = "https://codeberg.org/slidge/slidgram/issues"
Repository = "https://codeberg.org/slidge/slidgram"
"Chat room" = "https://conference.nicoco.fr:5281/muc_log/slidge/"
Documentation = "https://slidge.codeberg.page/docs/slidgram/main"

[project.scripts]
slidge = 'slidgram:main'

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["slidgram*"]

[tool.mypy]
files = ["slidgram"]
exclude = ["tests"]
check_untyped_defs = true
strict = false

[tool.ruff]
line-length = 88
exclude = ["tests"]

[tool.ruff.lint]
select = ["I"]

[tool.uv.sources]
slidge-dev-helpers = { git = "https://git.sr.ht/~nicoco/slidge-dev-helpers" }

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "codeberg"
url = "https://codeberg.org/api/packages/slidge/pypi/simple"
publish-url = "https://codeberg.org/api/packages/slidge/pypi"

[dependency-groups]
dev = [
    "furo>=2024.8.6",
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "ruff>=0.9.1",
    "slidge-dev-helpers",
    "sphinx-autoapi>=3.4.0",
    "sphinx-mdinclude>=0.6.2",
    "xmldiff>=2.7.0",
]

[tool.setuptools]
# FIXME: remove this when the setuptools upstream bug is fixed
# https://github.com/astral-sh/uv/issues/9513#issuecomment-2519527822
license-files = []
